### PR TITLE
Add io_uring sqe synchronization diagnostics and fix submission bug

### LINKED ISSUE #5350: [CI-TEST] Stress Test failed with iouring
It crashed, no log to report.

Failure here:
https://github.com/microsoft/msquic/actions/runs/16916730458/job/47932965211?pr=5327

### LINKED ISSUE #5490: [CI-TEST] Stress (Debug, linux, ubuntu-24.04, x64, quictls, -Sanitize, -Test, -UseIoUring)
Stress test failure in https://github.com/microsoft/msquic/pull/5483

### PR DESCRIPTION
**Pull request by mtfriesen**
## Description

_Describe the purpose of and changes within this Pull Request._

Add more debug assertions to detect certain unsynchronized patterns. While adding these and reviewing io_uring documentation, I realized one code path calls `io_uring_submit` without any external synchronization and fixed that too, after verifying the new diagnostics catch the error locally.

The symptoms should lead exactly to the io_uring flakiness we were seeing, so optimistically:

Resolves #5350
Resolves #5490

## Testing

_Do any existing tests cover this change? Are new tests needed?_

Builds and spins locally, and detects the bug fixed.

## Documentation

_Is there any documentation impact for this change?_

No.

### CODE REVIEW

File: src/inc/quic_platform_posix.h [hunk 1]
```diff
@@ -1121,22 +1162,28 @@ CxPlatEventQDequeue(
...
     if (Queue->NeedsSubmit) {
         //
-        // Review: can be batched with waits below.
+        // Review: can be batched with waits below if fully partitioned.
         //
-        io_uring_submit(&Queue->Ring);
+        CxPlatLockAcquire(&Queue->Lock);
+        CxPlatEventQSubmit(Queue);
         Queue->NeedsSubmit = FALSE;
+        CxPlatLockRelease(&Queue->Lock);
```
Comment (ProjectsByJackHe) [inline src/inc/quic_platform_posix.h:1175]: So, this is the key code change that fixes the flakiness?

The rest of the changes looks to be ASSERT modifications and wrapping io_uring_submit calls.

Comment (mtfriesen) [reply src/inc/quic_platform_posix.h:1175]: Yep, that's the actual fix. io_uring works a bit different than some of the other ring APIs, where in others the call into the kernel can be made thread-safe, in io_uring the submission modifies the submission ring and needs mutual exclusion with other submission code paths.

File: src/inc/quic_platform_posix.h [hunk 2]
```diff
@@ -1087,6 +1088,46 @@ CxPlatEventQCleanup(
...
+QUIC_INLINE
+struct io_uring_sqe*
+CxPlatEventGetSqe(
+    _In_ CXPLAT_EVENTQ* Queue
+    )
+{
+    struct io_uring_sqe* io_sqe;
+#if DEBUG
+    CxPlatLockAcquire(&Queue->Lock);
+    CXPLAT_DBG_ASSERT(Queue->SqContentionCount++ == 0);
```
Comment (guhetier) [inline src/inc/quic_platform_posix.h:1100]:
```suggestion
    CXPLAT_DBG_ASSERT(Queue->SqContentionCount == 0);
    Queue->SqContentionCount++;
```

For the sake of clarity, I'd split this. The 1 line saved is, in my opinion, not worth having to think about the postfix / prefix behaviors for `++` and `--`.

File: src/inc/quic_platform_posix.h [hunk 3]
```diff
@@ -1087,6 +1088,46 @@ CxPlatEventQCleanup(
...
+    CxPlatLockAcquire(&Queue->Lock);
+    CXPLAT_DBG_ASSERT(--Queue->SqContentionCount == 0);
+    CxPlatLockRelease(&Queue->Lock);
+#endif
+    return io_sqe;
+}
+
+QUIC_INLINE
+void
+CxPlatEventQSubmit(
```
Comment (guhetier) [inline src/inc/quic_platform_posix.h:1114]: The issue was that this call needs to happen under lock, right?
Could we add some SAL annotation / comment?
Since the lock is re-entrant, should we simply take the lock inside of the function?

File: src/inc/quic_platform_posix.h (hunk 2 above)
Comment (mtfriesen) [reply src/inc/quic_platform_posix.h:1100]: 6 of one, half dozen the other. Sticking with concision.

File: src/inc/quic_platform_posix.h (hunk 3 above)
Comment (mtfriesen) [reply src/inc/quic_platform_posix.h:1114]: No lock is required, and eventually the goal is to remove all locks from the io_uring implementation and rely on internal/external end-to-end synchronization via explicit partitioning.

Comment (guhetier) [reply src/inc/quic_platform_posix.h:1114]: I'm not sure I understand. On another comment, you mention that the fix is to call this under lock because these call needs synchronization for io_uring. If you have a pointer to an explanation, I'd take it.

Comment (mtfriesen) [reply src/inc/quic_platform_posix.h:1114]: io_uring is not thread-safe for many operations; callers of io_uring APIs must provide some external synchronization.

This PR fixes a thread-unsafe operation by acquiring a lock. This function does not require holding a lock.

**Comment by mtfriesen** [comment]
@microsoft-github-policy-service rerun
