### PR TITLE
Wait for all connections to be freed during registration close

### LINKED ISSUE #472: Crash in msquic!QuicWorkerQueueConnection
### Describe the bug

On a [recent AZP run](https://dev.azure.com/ms/msquic/_build/results?buildId=85629&view=results) for a PR, we hit a crash during the **AppData/WithSend0RttArgs1.Send0Rtt/62** test case:

```
==================================================================================
 msquictest.exe.6280.dmp
==================================================================================
 # Child-SP          RetAddr           Call Site
00 00000092`1dafda78 00007ffb`a47aca8e ntdll!ZwWaitForMultipleObjects+0x14
01 00000092`1dafda80 00007ffb`a47ac97e KERNELBASE!WaitForMultipleObjectsEx+0xfe
02 00000092`1dafdd80 00007ffb`a6d87acf KERNELBASE!WaitForMultipleObjects+0xe
03 00000092`1dafddc0 00007ffb`a6d8757c kernel32!WerpLaunchAeDebug+0x285f
04 00000092`1dafdee0 00007ffb`a47d719e kernel32!WerpLaunchAeDebug+0x230c
05 00000092`1dafdf20 00007ffb`a7ab820b KERNELBASE!UnhandledExceptionFilter+0x35e
06 00000092`1dafe030 00007ffb`a7a9fd56 ntdll!memset+0x1c8b
07 00000092`1dafe070 00007ffb`a7ab479f ntdll!_C_specific_handler+0x96
08 00000092`1dafe0e0 00007ffb`a7a14bef ntdll!_chkstk+0x11f
09 00000092`1dafe110 00007ffb`a7ab350e ntdll!RtlWalkFrameChain+0x14bf
0a 00000092`1dafe840 00007ffb`a7a5df33 ntdll!KiUserExceptionDispatcher+0x2e
0b 00000092`1dafef40 00007ffb`a7a19bbc ntdll!EtwNotificationRegister+0x2c3
0c 00000092`1dafefb0 00007ffb`a7a19ad0 ntdll!RtlEnterCriticalSection+0x12c
0d 00000092`1dafefe0 00007ffb`6c521ca6 ntdll!RtlEnterCriticalSection+0x40
0e 00000092`1daff010 00007ffb`6c528065 msquic!QuicWorkerQueueConnection+0x86
0f 00000092`1daff050 00007ffb`6c52b7d6 msquic!QuicConnQueueOper+0x55
10 00000092`1daff080 00007ffb`6c513a29 msquic!QuicConnQueueRecvDatagrams+0x316
11 00000092`1daff320 00007ffb`6c50fc24 msquic!QuicBindingDeliverDatagrams+0x499
12 00000092`1daff400 00007ffb`6c587a32 msquic!QuicBindingReceive+0x594
13 00000092`1daff500 00007ffb`6c586299 msquic!QuicDataPathRecvComplete+0xad2
14 00000092`1daffcd0 00007ffb`a6d37974 msquic!QuicDataPathWorkerThread+0x339
15 00000092`1daffdd0 00007ffb`a7a7a271 kernel32!BaseThreadInitThunk+0x14
16 00000092`1daffe00 00000000`00000000 ntdll!RtlUserThreadStart+0x21
==================================================================================
```

Artifacts are temporarily available here: https://dev.azure.com/ms/msquic/_build/results?buildId=85629&view=artifacts&type=publishedArtifacts

### PR DESCRIPTION
**Pull request by ThadHouse**
If the connection received data after the registration worker pools were free, we hit a crash. This is caused by a race between cleaning up a connection and the binding receiving data. If we wait for the connections to be fully clean before cleaning up the worker threads, the race is avoided.

Should fix #472 but needs to be tested

### CODE REVIEW

File: src/core/connection.c [hunk 1]
```diff
@@ -117,6 +117,7 @@ QuicConnAlloc(
     QuicSendInitialize(&Connection->Send);
     QuicLossDetectionInitialize(&Connection->LossDetection);
     QuicDatagramInitialize(&Connection->Datagram);
+    QuicRundownAcquire(&Session->Registration->ConnectionRundown);
```
Comment (nibanks) [inline src/core/connection.c:120]: Server side connections cannot acquire the ref in alloc, as they don't have a registration associated until they've been accepted by a listener.

File: src/core/connection.c [hunk 2]
```diff
@@ -372,6 +373,7 @@ QuicConnFree(
         QuicLibraryReleaseBinding(Path->Binding);
         Path->Binding = NULL;
     }
+    QuicRundownRelease(&Connection->Registration->ConnectionRundown);
```
Comment (nibanks) [inline src/core/connection.c:376]: There is no guarantee a connection will have a registration associated to it when it's freed. It might not have ever been accepted by a listener.

File: src/core/connection.c [hunk 3]
```diff
@@ -372,6 +372,9 @@ QuicConnFree(
         QuicLibraryReleaseBinding(Path->Binding);
         Path->Binding = NULL;
     }
+    if (Connection->Registration != NULL) {
+        QuicRundownRelease(&Connection->Registration->ConnectionRundown);
+    }
```
Comment (nibanks) [inline src/core/connection.c:377]: Let's put this after `QuicSessionUnregisterConnection` below.

**Comment by nibanks** [comment]
Looks like spinquic failed. Can you take a look before merging?
https://dev.azure.com/ms/msquic/_build/results?buildId=85821&view=logs&j=4e08e7db-7517-5f8d-8ec9-334a70dc8fc2&t=a1521c54-938f-5e18-a5ca-59dc8be93bbb

**Comment by ThadHouse** [comment]
Ok. Looks like it was successful this time.
