### PR TITLE
Fix XDP Cleanup on Init Failure Crash

### LINKED ISSUE #3103: Crash on CxPlatDataPathUninitializeComplete
### Describe the bug

Spinquic hit a crash in the following callstack when running for XDP:
```
 # Child-SP          RetAddr               Call Site
00 000000dc`200ff340 00007ffe`09663c59     msquic!CxPlatRefDecrement+0x42 [D:\a\1\msquic\src\inc\quic_platform_winuser.h @ 565] 
01 000000dc`200ff360 00007ffe`096721d7     msquic!CxPlatDataPathUninitializeComplete+0xf9 [D:\a\1\msquic\src\platform\datapath_raw.c @ 221] 
02 000000dc`200ff3a0 00007ffe`0966f551     msquic!CxPlatDpRawRelease+0x77 [D:\a\1\msquic\src\platform\datapath_raw_xdp.c @ 1160] 
03 000000dc`200ff3e0 00007ffe`09677f43     msquic!CxPlatXdpExecute+0x41 [D:\a\1\msquic\src\platform\datapath_raw_xdp.c @ 1615] 
04 000000dc`200ff430 00007ffe`09677b82     msquic!CxPlatRunExecutionContexts+0xc3 [D:\a\1\msquic\src\platform\platform_worker.c @ 361] 
05 000000dc`200ff4a0 00007ffe`43074ed0     msquic!CxPlatWorkerThread+0x162 [D:\a\1\msquic\src\platform\platform_worker.c @ 416] 
06 000000dc`200ff8a0 00007ffe`4423e39b     kernel32!BaseThreadInitThunk+0x10
07 000000dc`200ff8d0 00000000`00000000     ntdll!RtlUserThreadStart+0x2b
```
https://dev.azure.com/ms/msquic/_build/results?buildId=379703&view=results

### Affected OS

- [ ] All
- [X] Windows Server 2022
- [X] Windows 11, version 22H2
- [X] Windows 11, version 21H2
- [X] Windows Insider Preview (specify affected build below)
- [ ] Ubuntu
- [ ] Debian
- [ ] Other (specify below)

### Additional OS information

_No response_

### MsQuic version

main

### Steps taken to reproduce bug

Run spinquic with XDP.

### Expected behavior

Spinquic didn't crash.

### Actual outcome

Crash

### Additional details

_No response_

### PR DESCRIPTION
**Pull request by nibanks**
## Description

Fixes #3103. Reorders the cleanup code for initialization failure.

## Testing

Existing CI (spinquic).

## Documentation

N/A

### CODE REVIEW

File: src/platform/datapath_raw.c [hunk 1]
```diff
@@ -182,6 +182,7 @@ CxPlatDataPathInitialize(
                 CxPlatSockPoolUninitialize(&DataPath->SocketPool);
             }
             CXPLAT_FREE(DataPath, QUIC_POOL_DATAPATH);
+            CxPlatRundownRelease(&CxPlatWorkerRundown);
```
Comment (anrossi) [inline src/platform/datapath_raw.c:185]: Don't you want to `rundownRelease` in all error paths?

Comment (nibanks) [reply src/platform/datapath_raw.c:185]: No. That's the bug. If `DpRawInitialized` then it will eventually be released when `CxPlatDpRawUninitialize` complete (possibly asynchronously).
