### PR TITLE
Fix Frame Type Encoding Issues

### LINKED ISSUE #1313: Frame Type Decoding Assumes Single Byte Encoding
### Describe the bug

The frame decoding logic was assuming the peer always used a single byte encoding for frame types. The ACK_FREQUENCY frame broke that assumption. Luckily, since support for new frames (that break this assumption) are negotiated, older versions of MsQuic are generally unaffected by this assumption because it never used frames that didn't fit. Only the newest code needs MUST be updated.

### Steps to reproduce the behavior

1. Run interop test between picoquic and msquic.
2. MsQuic aborts the connection with a FRAME_ENCODING_ERROR because of the "unknown" frame.

### Expected vs actual behavior

The connection should continue as normal and not abort.

### PR DESCRIPTION
**Pull request by nibanks**
Fixes #1313. The encoding is actually a variable length integer, not a simple byte. Up until the ACK_FREQUENCY frame, the assumption held, but now that we've added support for that, it no longer holds and breaks interop.

### CODE REVIEW

File: src/core/sent_packet_metadata.h [hunk 1]
```diff
@@ -74,6 +74,10 @@ typedef struct QUIC_SENT_FRAME_METADATA {
 
 } QUIC_SENT_FRAME_METADATA;
 
+CXPLAT_STATIC_ASSERT(
+    QUIC_FRAME_MAX_SUPPORTED <= (uint64_t)UINT8_MAX,
+    "Metadata 'Type' field above assumes frames types fit in 8-bits");
```
Comment (anrossi) [inline src/core/sent_packet_metadata.h:79]: This only applies for packets that are sent, right? Not received?

File: src/core/unittest/SpinFrame.cpp [hunk 2]
```diff
@@ -47,7 +47,11 @@ TEST(SpinFrame, SpinFrame1000000)
     BOOLEAN InvalidFrame;
     uint8_t Buffer[255];
     uint8_t BufferLength = 0;
+
     uint8_t FrameType;
+    CXPLAT_STATIC_ASSERT(
+        QUIC_FRAME_MAX_SUPPORTED <= (uint64_t)UINT8_MAX,
+        "Tests below assumes frames fit in 8-bits");
```
Comment (anrossi) [inline src/core/unittest/SpinFrame.cpp:54]: Can you add an AckFrequency frame case to this test?

Comment (anrossi) [reply src/core/unittest/SpinFrame.cpp:54]: Also, add a case in the QUIC_FRAME_TYPE ostream overload to pretty print the Ack Frequency frame

File: src/core/sent_packet_metadata.h (hunk 1 above)
Comment (nibanks) [reply src/core/sent_packet_metadata.h:79]: Correct. It's "sent" metadata.

File: src/core/unittest/SpinFrame.cpp (hunk 2 above)
Comment (nibanks) [reply src/core/unittest/SpinFrame.cpp:54]: We already have a test case for the frame.

**Review by anrossi — APPROVED** [review]
