### PR TITLE
Fix Bug in Allocation Failure Path of OnPacketSent

### LINKED ISSUE #1570: When ACK tracking data fails to allocate on send, immediately trigger OnLoss handler
If the ACK tracking data fails to allocate, then the sender has no idea if the data was ACKed or lost, so call the OnLoss handler inline. Look at `QuicLossDetectionOnPacketSent`

### PR DESCRIPTION
**Pull request by nibanks**
Fixes #1570.

### CODE REVIEW

File: src/core/loss_detection.c [hunk 1]
```diff
@@ -401,21 +401,30 @@ QuicLossDetectionOnPacketSent(
...
     // Allocate a copy of the packet metadata.
     //
-    SentPacket =
+    QUIC_SENT_PACKET_METADATA* SentPacket =
         QuicSentPacketPoolGetPacketMetadata(
             &Connection->Worker->SentPacketPool, TempSentPacket->FrameCount);
     if (SentPacket == NULL) {
+        //
+        // We can't allocate the memory to permanently track this packet so just
+        // go ahead and immeadiate clean up and mark the data in it as lost.
```
Comment (ThadHouse) [inline src/core/loss_detection.c:416]: Spelling of immediately

**Review by ThadHouse — APPROVED** [review]
