### PR TITLE
Fixes for clang-cl

### LINKED ISSUE #1310: clang-cl error in 'core/stream.c'
Compiling with `clang-cl` v.11 generates this error for `src/core.c`:
```
core/stream.c(454,1): error: conflicting types for 'QuicStreamShutdown'
QuicStreamShutdown(
^
core/stream.h(542,1): note: previous declaration is here
QuicStreamShutdown(
^
1 error generated.
```

Since in the prototype, the `Flags` is an `uint32_t`. Whereas in the implementation it's an
`enum QUIC_STREAM_SHUTDOWN_FLAGS`. `clang-cl` is rather picky on such things; many warnings like:

`anonymous structs are a Microsoft extension [-Wmicrosoft-anon-tag]`

I fixed it by simply:
```diff
--- a/core/stream.h 2021-03-04 13:48:31
+++ b/core/stream.h  2021-03-04 16:37:26
@@ -537,11 +537,13 @@
 //
 // Initiates an asychronous shutdown of one or both directions of the stream.
 //
+enum QUIC_STREAM_SHUTDOWN_FLAGS; // in 'core/msquic.h'
+
 _IRQL_requires_max_(PASSIVE_LEVEL)
 void
 QuicStreamShutdown(
     _In_ QUIC_STREAM* Stream,
-    _In_ uint32_t Flags,
+    _In_ enum QUIC_STREAM_SHUTDOWN_FLAGS Flags,
     _In_ QUIC_VAR_INT ErrorCode
     );
```

### PR DESCRIPTION
**Pull request by nibanks**
Fixes #1310. FYI @gvanem.

### CODE REVIEW

**Review by anrossi — APPROVED** [review]

File: src/platform/datapath_winuser.c [hunk 1]
```diff
@@ -76,13 +76,13 @@ CxPlatFuzzerRecvMsg(
 //
 #define URO_MAX_DATAGRAMS_PER_INDICATION    64
 
-static_assert(
+CXPLAT_STATIC_ASSERT(
     sizeof(QUIC_BUFFER) == sizeof(WSABUF),
     "WSABUF is assumed to be interchangeable for QUIC_BUFFER");
-static_assert(
+CXPLAT_STATIC_ASSERT(
```
Comment (gvanem) [inline src/platform/datapath_winuser.c:82]: That didn't help. `clang-cl` still says:
```c
platform/datapath_winuser.c(84,5): error: static_assert expression is not an integral constant expression
    FIELD_OFFSET(QUIC_BUFFER, Length) == FIELD_OFFSET(WSABUF, len),
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
f:\ProgramFiler-x86\WindowsKits\Include\10.0.19041.0\um\winnt.h(1205,38): note: expanded from macro 'FIELD_OFFSET'
#define FIELD_OFFSET(type, field)    ((LONG)(LONG_PTR)&(((type *)0)->field))                                     ^
```

Although the preprocessed output of line 84 seems correct:
```
_Static_assert ( ( (LONG) (LONG_PTR) & ( ( (QUIC_BUFFER *) 0)->Length)) == 
   ( (LONG) (LONG_PTR) & ( ( (WSABUF *) 0)->len)),  "WSABUF is assumed to be interchangeable for QUIC_BUFFER");
```

File: src/platform/datapath_winuser.c [hunk 2]
```diff
@@ -76,13 +76,13 @@ CxPlatFuzzerRecvMsg(
...
     FIELD_OFFSET(QUIC_BUFFER, Length) == FIELD_OFFSET(WSABUF, len),
     "WSABUF is assumed to be interchangeable for QUIC_BUFFER");
-static_assert(
+CXPLAT_STATIC_ASSERT(
```
Comment (gvanem) [inline src/platform/datapath_winuser.c:85]: Same clang-cl error here. Curiously the 1st `CXPLAT_STATIC_ASSERT()` on line 79 is no sweat for clang-cl.
