### PR TITLE
Switch uses of min and max to CXPLAT_MIN and CXPLAT_MAX

### LINKED ISSUE #1697: Remove use of min macro.
The min macro likes to interfere with things. Libraries on windows usually know how to handle this, but on linux this is not the case. A big hitter is std library, where a definition of the min macro can make them completely fail to compile. We should define our own min macro with a different name to use.

### PR DESCRIPTION
**Pull request by ThadHouse**
The min and max macros in Windows.h are a huge pain point, however most windows libraries, including the stl, are able to handle this. However, we define these macros on posix, which most posix libraries, including the C++ standard libraries (which have min and max functions) completely breaks. Instead of defining these on posix, define a common CXPLAT_MIN and CXPLAT_MAX macro that works on all platforms, and doesn't interfere with use in posix applications and libraries.

Closes #1697

### CODE REVIEW

File: src/core/send_buffer.c [hunk 1]
```diff
@@ -46,7 +46,7 @@
     streams, and its legacy APIs don't let it pass the problem further up the
     stack to the layer that really knows.
 
-    So then, we indicate min(SendBuffer.IdealBytes, Stream.SendWindow) as the
+    So then, we indicate CXPLAT_MIN(SendBuffer.IdealBytes, Stream.SendWindow) as the
```
Comment (nibanks) [inline src/core/send_buffer.c:49]: Can you go through and either revert the comment changes or fix up the line lengths?

**Review by anrossi — APPROVED** [review]

**Review by nibanks — APPROVED** [review]
