### PR TITLE
More SpinQuic Features and Associated Fixes

### LINKED ISSUE #387: Update SpinQuic for Latest API Changes
SpinQuic has lagged a bit, as far as supporting "spinning" the latest API features. One notable feature that is missing support is the Datagram stuff. I believe a few new parameters have also been added. These need to be integrated into SpinQuic.

### PR DESCRIPTION
**Pull request by nibanks**
- Removes all the `PRINT` calls from spinquic because they are too numerous and bog down the system when running for minutes at a time.
- Adds multiple possible length buffers to use for sending on streams and in datagrams.
- Fixes the issues found after adding the above, mostly in the datagram code.

Fixes #387

### CODE REVIEW

File: src/core/datagram.c [hunk 1]
```diff
@@ -167,6 +190,45 @@ QuicDatagramSendShutdown(
...
+            }
+            *SendQueue = SendRequest->Next;
+            QuicDatagramCancelSend(Connection, SendRequest);
+        } else {
+            SendQueue = &((*SendQueue)->Next);
+        }
+    }
+    Datagram->SendQueueTail = SendQueue;
+
+    /* if (Connection->Crypto.TlsState.WriteKey >= QUIC_PACKET_KEY_1_RTT) */ {
```
Comment (nibanks) [inline src/core/datagram.c:223]: TODO - Figure out if we need this or not.

File: src/core/datagram.c [hunk 2]
```diff
@@ -389,12 +482,15 @@ QuicDatagramWriteFrame(
                 &Builder->DatagramLength,
                 AvailableBufferLength,
                 (uint8_t*)Builder->Datagram->Buffer);
-        if (!HadRoomForDatagram && Builder->Metadata->FrameCount != 0) {
+        if (!HadRoomForDatagram) {
             //
-            // Part of the packet was used already and we didn't have room to frame
-            // this datagram. We need to try again in an unused packet.
+            // We didn't have room to frame this datagram. This should only
+            // happen if because there was other data in the packet already.
```
Comment (nibanks) [inline src/core/datagram.c:488]: Fix comment

File: src/tools/spin/spinquic.cpp [hunk 3]
```diff
@@ -39,14 +24,21 @@ const QUIC_BUFFER Buffers[2] = {
...
+       printf("%s:%d !'%s' !\n", __FILE__, __LINE__, #x); \
+       exit(10); \
+    } \
+} while (0);
+
 template<typename T>
-T& GetRandomFromVector(std::vector<T> &vec) {
-    return vec.at(rand() % vec.size());
+T GetRandom(T UpperBound) {
+    return (T)(rand() % (int)UpperBound);
```
Comment (anrossi) [inline src/tools/spin/spinquic.cpp:36]: Shouldn't this use QuicGetRandom()?

File: src/tools/spin/spinquic.cpp [hunk 4]
```diff
@@ -439,16 +430,13 @@ void Spin(LockableVector<HQUIC>& Connections, bool IsServer)
 
                 HQUIC Connection;
                 HQUIC Session = GetRandomFromVector(Sessions);
-                PRINT("MsQuic->ConnectionOpen(%p, ...) = ", Session);
```
Comment (anrossi) [inline src/tools/spin/spinquic.cpp:442]: Instead of removing all the PRINT statements, can they be turned into ETW/WPP trace statements?

File: src/tools/spin/spinquic.cpp (hunk 3 above)
Comment (nibanks) [reply src/tools/spin/spinquic.cpp:36]: I had tried and I was seeing weird results. I'm going to leave it for now.

File: src/tools/spin/spinquic.cpp [hunk 5]
```diff
@@ -498,10 +479,7 @@ void Spin(LockableVector<HQUIC>& Connections, bool IsServer)
                 std::lock_guard<std::mutex> Lock(ctx->Lock);
                 auto Stream = ctx->TryGetStream();
                 if (Stream == nullptr) continue;
-                PRINT("MsQuic->StreamStart(%p, ...) = ", Stream);
-                QUIC_STATUS Status = MsQuic->StreamStart(Stream, (QUIC_STREAM_START_FLAGS)(rand() % 2) | QUIC_STREAM_START_FLAG_ASYNC);
-                PRINT("0x%x\n", Status);
-                UNREFERENCED_PARAMETER(Status);
+                MsQuic->StreamStart(Stream, (QUIC_STREAM_START_FLAGS)(rand() % 2) | QUIC_STREAM_START_FLAG_ASYNC);
```
Comment (anrossi) [inline src/tools/spin/spinquic.cpp:482]: convert `rand()` call to `GetRandom()`

File: src/tools/spin/spinquic.cpp (hunk 4 above)
Comment (nibanks) [reply src/tools/spin/spinquic.cpp:442]: We already have events for API calls in msquic.

File: src/tools/spin/spinquic.cpp (hunk 3 above)
Comment (anrossi) [reply src/tools/spin/spinquic.cpp:36]: I see that reproducibility is needed from the RNG, so `rand()` makes sense.

File: src/core/api.c [hunk 6]
```diff
@@ -1278,31 +1278,11 @@ MsQuicDatagramSend(
...
     QUIC_TEL_ASSERT(!Connection->State.Freed);
 
-    if (!Connection->Datagram.SendEnabled) {
-        QuicTraceEvent(
-            ConnError,
-            "[conn][%p] ERROR, %s.",
-            Connection,
-            "Datagrams not enabled by peer");
-        Status = QUIC_STATUS_NOT_SUPPORTED;
-        goto Error;
```
Comment (anrossi) [inline src/core/api.c:1288]: Isn't it better to fail early so the app knows not to try to send datagrams?

Comment (nibanks) [reply src/core/api.c:1288]: It's a matter of synchronization. Also, it's not worth optimizing for the negative case here, IMO. If they're incorrectly trying to queue datagrams, I'm Ok if it ends up doing a pool alloc followed by a pool free.

Comment (anrossi) [reply src/core/api.c:1288]: How is the failure bubbled up to the app, if at all?

Comment (nibanks) [reply src/core/api.c:1288]: `QuicDatagramQueueSend` will fail the error back to the app.
