### PR TITLE
Reset Datagram SendFlag when writing last datagram and out of buffer

### LINKED ISSUE #425: Assertion Failure for failure to write in QuicSendWriteFrames
### Describe the bug

QuicSendWriteFrames is asserting that we didn't run out of room in the frame, but nothing was added to the frame.

https://microsoft.visualstudio.com/OS/_build/results?buildId=23925449&view=results

```
==================================================================================
 # Child-SP          RetAddr           Call Site
00 000000a0`68cfcaf8 00007fff`9a98ca8e ntdll!ZwWaitForMultipleObjects+0x14
01 000000a0`68cfcb00 00007fff`9a98c97e KERNELBASE!WaitForMultipleObjectsEx+0xfe
02 000000a0`68cfce00 00007fff`9b2b7acf KERNELBASE!WaitForMultipleObjects+0xe
03 000000a0`68cfce40 00007fff`9b2b757c kernel32!WerpLaunchAeDebug+0x285f
04 000000a0`68cfcf60 00007fff`9a9b719e kernel32!WerpLaunchAeDebug+0x230c
05 000000a0`68cfcfa0 00007fff`9dda820b KERNELBASE!UnhandledExceptionFilter+0x35e
06 000000a0`68cfd0b0 00007fff`9dd8fd56 ntdll!memset+0x1c8b
07 000000a0`68cfd0f0 00007fff`9dda479f ntdll!_C_specific_handler+0x96
08 000000a0`68cfd160 00007fff`9dd04bef ntdll!_chkstk+0x11f
09 000000a0`68cfd190 00007fff`9dda350e ntdll!RtlWalkFrameChain+0x14bf
0a 000000a0`68cfd8c0 00007fff`615dfeff ntdll!KiUserExceptionDispatcher+0x2e
0b 000000a0`68cfe6a0 00007fff`615dd81f msquic!QuicSendWriteFrames+0x122f
0c 000000a0`68cfe920 00007fff`615b8bc8 msquic!QuicSendFlush+0x4ff
0d 000000a0`68cff510 00007fff`615b42bf msquic!QuicConnDrainOperations+0x398
0e 000000a0`68cff7b0 00007fff`615b3047 msquic!QuicWorkerProcessConnection+0x24f
0f 000000a0`68cffa70 00007fff`9b267974 msquic!QuicWorkerThread+0xd7
10 000000a0`68cffd10 00007fff`9dd6a271 kernel32!BaseThreadInitThunk+0x14
11 000000a0`68cffd40 00000000`00000000 ntdll!RtlUserThreadStart+0x21
==================================================================================

```

### PR DESCRIPTION
**Pull request by ThadHouse**
If flag isn't reset, we get in an invalid state where we are told to write a datagram, but have none to write.

Also adds validation to ensure when leaving QuicDatagramWriteFrame the datagram is valid.

Closes #425

### CODE REVIEW

File: src/core/datagram.c [hunk 1]
```diff
@@ -469,6 +469,7 @@ QuicDatagramWriteFrame(
 {
     QUIC_CONNECTION* Connection = QuicDatagramGetConnection(Datagram);
     QUIC_DBG_ASSERT(Datagram->SendEnabled);
+    BOOLEAN ExitValue = FALSE;
```
Comment (nibanks) [inline src/core/datagram.c:472]: Let's rename it to `Result` instead.

File: src/core/datagram.c [hunk 2]
```diff
@@ -524,13 +527,21 @@ QuicDatagramWriteFrame(
             SendRequest,
             &Builder->Metadata->Frames[Builder->Metadata->FrameCount].DATAGRAM.ClientContext);
         if (++Builder->Metadata->FrameCount == QUIC_MAX_FRAMES_PER_PACKET) {
-            return TRUE;
+            if (Datagram->SendQueue == NULL) {
+                Connection->Send.SendFlags &= ~QUIC_CONN_SEND_FLAG_DATAGRAM;
```
Comment (nibanks) [inline src/core/datagram.c:531]: Should we just put put this after `Exit`?

File: src/core/datagram.c [hunk 3]
```diff
@@ -524,13 +527,21 @@ QuicDatagramWriteFrame(
...
+            }
+            ExitValue = TRUE;
+            goto Exit;
         }
     }
 
     Connection->Send.SendFlags &= ~QUIC_CONN_SEND_FLAG_DATAGRAM;
+    ExitValue = FALSE;
```
Comment (nibanks) [inline src/core/datagram.c:539]: It was already defaulted to `FALSE`
