### PR TITLE
Fix QTIP port selection

### LINKED ISSUE #5346: [CI-TEST] SendQtip failed
AppData/WithSendArgs1.SendQtip/272 failed

```
[ RUN      ] AppData/WithSendArgs1.SendQtip/272
C:\a\msquic\msquic\src\test\lib\TestConnection.cpp(864): error: Unexpected transport Close Error, expected=0x0, actual=0x80410003
C:\a\msquic\msquic\src\test\lib\DataTest.cpp(146): error: Not all data sent.
C:\a\msquic\msquic\src\test\lib\DataTest.cpp(149): error: Not all data received.
C:\a\msquic\msquic\src\test\lib\DataTest.cpp(146): error: Not all data sent.
C:\a\msquic\msquic\src\test\lib\DataTest.cpp(149): error: Not all data received.
C:\a\msquic\msquic\src\test\lib\DataTest.cpp(231): error: Connection->GetTransportClosed() not false
C:\a\msquic\msquic\src\test\lib\DataTest.cpp(599): error: Wait for server to complete timed out after 3000 ms.
[  FAILED  ] AppData/WithSendArgs1.SendQtip/272, where GetParam() = v6/0/4/2/NoSendBuffer/Bidi/Client (3090 ms)
```

Link to failure:
https://github.com/microsoft/msquic/actions/runs/16885870731/job/47833919388

### PR DESCRIPTION
**Pull request by guhetier**
## Description

Fixes #5346.

When creating a QTIP listener with a wildcard port:
- a UDP socket is created first (to reserve the UDP port as XDP will take it over), and the OS would assign an ephemeral port to it
- a TCP socket is created second (to reserve the TCP port as XDP will take it over)
    - but instead of re-using the same port, the initial config was re-used, and the OS would assign a different ephemeral port
    - this second port would override the first one in the MsQuic socket config

The main consequences of this bug are:
- the right UDP port was not reserved when creating a listener with a wildcard port
- if later on, the OS assigned the UDP port matching the listener TCP port, MsQuic would fail to create a binding (causing the test failure we observed)

Creating a listener without a port set is largely a test scenario.
Creating a client connection with an unspecified a port was ok because only a TCP or a UDP socket is created for client connection.

## Testing

C/I. We should add some test to validate port reservation in XDP scenarios, but it will take efforts to enable test to create sockets cross-platform.

## Documentation

N/A

### CODE REVIEW

File: src/platform/datapath_raw_win.c [hunk 1]
```diff
@@ -123,28 +123,34 @@ RawSocketCreateUdp(
...
+    // config doesn't specify them.
+    //
+    CXPLAT_DBG_ASSERT(
+        Config->RemoteAddress == NULL ||
+        QuicAddrCompare(&Socket->RemoteAddress, Config->RemoteAddress));
+    CXPLAT_DBG_ASSERT(
+        Config->LocalAddress == NULL ||
+        QuicAddrGetPort(Config->LocalAddress) == 0 ||
+        QuicAddrGetPort(&Socket->LocalAddress) == QuicAddrGetPort(Config->LocalAddress));
+    CXPLAT_DBG_ASSERT(QuicAddrGetPort(&Socket->LocalAddress) != 0);
```
Comment (ProjectsByJackHe) [inline src/platform/datapath_raw_win.c]: As discussed offline, this won't be true in all scenarios.
