### PR TITLE
Reset TLS Unit Test Flags

### LINKED ISSUE #1369: TlsTest Failure from SEC_I_INCOMPLETE_CREDENTIALS
### Describe the bug

When running the TlsTest.* unit tests not in isolated mode, we seem to get `SEC_I_INCOMPLETE_CREDENTIALS` from the second test case (Handshake).

### Steps to reproduce the behavior

1. Run `.\scripts\test.ps1 -Filter TlsTest.*`
2. View output
3. See errors.

### Expected vs actual behavior

I'm unsure why, but if we run `Handshake` test right after `Initialize`, we are getting `SEC_I_INCOMPLETE_CREDENTIALS` when we call `AcceptSecurityContext: 

```
    84 [0]1D18.66B0::2021/03/24-09:02:30.691791700 [Microsoft-Quic][conn][0xE9D12FF040] TLS context Created
    85 [0]1D18.66B0::2021/03/24-09:02:30.691793600 [Microsoft-Quic][conn][0xE9D12FF150] TLS context Created
    86 [0]1D18.66B0::2021/03/24-09:02:30.691800200 [Microsoft-Quic][conn][0xE9D12FF150] Processing 0 received bytes
    88 [0]1D18.66B0::2021/03/24-09:02:30.692152600 [Microsoft-Quic][conn][0xE9D12FF150] Consumed 0 bytes
    89 [0]1D18.66B0::2021/03/24-09:02:30.692154300 [Microsoft-Quic][conn][0xE9D12FF150] Produced 257 bytes
    90 [0]1D18.66B0::2021/03/24-09:02:30.692159400 [Microsoft-Quic][conn][0xE9D12FF040] Processing 257 received bytes
    91 [1]1D18.66B0::2021/03/24-09:02:30.764576400 [Microsoft-Quic][conn][0xE9D12FF040] Key Ready Type, 2 [90 to 1290]
    92 [1]1D18.66B0::2021/03/24-09:02:30.764580200 [Microsoft-Quic][conn][0xE9D12FF040] Key Ready Type, 1 [0 to 0]
    93 [1]1D18.66B0::2021/03/24-09:02:30.764583000 [Microsoft-Quic][conn][0xE9D12FF040] Key Ready Type, 2 [0 to 0]
    94 [1]1D18.66B0::2021/03/24-09:02:30.764585300 [Microsoft-Quic][conn][0xE9D12FF040] Consumed 257 bytes
    99 [1]1D18.66B0::2021/03/24-09:02:30.764789000 [Microsoft-Quic][conn][0xE9D12FF040] Reading Handshake data starts now
   104 [1]1D18.66B0::2021/03/24-09:02:30.764819600 [Microsoft-Quic][conn][0xE9D12FF040] Writing Handshake data starts at 90
   109 [1]1D18.66B0::2021/03/24-09:02:30.764848700 [Microsoft-Quic][conn][0xE9D12FF040] Writing 1-RTT data starts at 1290
   110 [1]1D18.66B0::2021/03/24-09:02:30.764851300 [Microsoft-Quic][conn][0xE9D12FF040] Produced 1290 bytes
   111 [1]1D18.66B0::2021/03/24-09:02:30.764858300 [Microsoft-Quic][conn][0xE9D12FF150] Processing 90 received bytes
   112 [1]1D18.66B0::2021/03/24-09:02:30.765399100 [Microsoft-Quic][conn][0xE9D12FF150] Key Ready Type, 2 [0 to 0]
   113 [1]1D18.66B0::2021/03/24-09:02:30.765404600 [Microsoft-Quic][conn][0xE9D12FF150] Key Ready Type, 1 [0 to 0]
   114 [1]1D18.66B0::2021/03/24-09:02:30.765407600 [Microsoft-Quic][conn][0xE9D12FF150] Consumed 90 bytes
   119 [1]1D18.66B0::2021/03/24-09:02:30.765429900 [Microsoft-Quic][conn][0xE9D12FF150] Reading Handshake data starts now
   124 [1]1D18.66B0::2021/03/24-09:02:30.765446600 [Microsoft-Quic][conn][0xE9D12FF150] Writing Handshake data starts at 257
   125 [1]1D18.66B0::2021/03/24-09:02:30.765449900 [Microsoft-Quic][conn][0xE9D12FF150] Processing 1200 received bytes
   127 [1]1D18.66B0::2021/03/24-09:02:30.765721500 [Microsoft-Quic][ tls][0xE9D12FF150] ERROR, 590624, Accept/InitializeSecurityContext.
```

### PR DESCRIPTION
**Pull request by nibanks**
Fixes #1369.

### CODE REVIEW

File: src/platform/unittest/TlsTest.cpp [hunk 1]
```diff
@@ -768,6 +771,7 @@ const CXPLAT_TLS_CALLBACKS TlsTest::TlsContext::TlsClientCallbacks = {
     TlsTest::TlsContext::OnPeerCertReceived
 };
 
+QUIC_CREDENTIAL_FLAGS TlsTest::SelfSignedCertParamsFlags = QUIC_CREDENTIAL_FLAG_NONE;
```
Comment (anrossi) [inline src/platform/unittest/TlsTest.cpp:774]: Double-chck that `CxPlatGetSelfSignedCert` doesn't set flags on the object by default. I think it does, so you might not want to start with `non`

Comment (nibanks) [reply src/platform/unittest/TlsTest.cpp:774]: I'm copying the default flags after we initialize the cert. This `none` is overwritten.

**Review by anrossi — APPROVED** [review]
