### PR TITLE
Limit number of cores in RPS Client test, fix RPS thread out of range bug

### LINKED ISSUE #792: RPS Performance Tests read processor array out of range.
We pass a uint8_t for processor index without also assuring that the passed index is within the size of the processor array. This causes out of range processor array reading.

### PR DESCRIPTION
**Pull request by ThadHouse**
Closes #792

### CODE REVIEW

File: src/perf/lib/RpsClient.cpp [hunk 1]
```diff
@@ -136,10 +136,17 @@ RpsClient::Start(
     }
 
     QUIC_STATUS Status = QUIC_STATUS_SUCCESS;
+    uint32_t ActiveProcCount = QuicProcActiveCount();
```
Comment (nibanks) [inline src/perf/lib/RpsClient.cpp:139]: I think you should only need to leave 1 core free; specifically core 0 (so add one to the index below).

Comment (nibanks) [reply src/perf/lib/RpsClient.cpp:139]: Actually, now I realize you're trying to explicitly leave cores free in the second group. But one should still be enough.

Comment (ThadHouse) [reply src/perf/lib/RpsClient.cpp:139]: The reason I went 2 was because of hyperthreading. Usually the hyperthread core is the 2nd one in a pair. So pulling 2 in general removes an entire physical core and it's hyperthread pair

Comment (nibanks) [reply src/perf/lib/RpsClient.cpp:139]: Ok.

**Comment by ThadHouse** [comment]
Closes #792

**Comment by ThadHouse** [comment]
This doesn't hurt perf, and is within the margin of error, so we're good.
