### PR TITLE
Ignore Retry packets when connection is shutting down.

### LINKED ISSUE #1767: Client can fail to process part of server flight and still accept stateless retry
### Describe the bug

If a client fails partially processing frames from a properly-decrypted server handshake packet, it won't correctly block retry packets. It should set `GotFirstServerResponse` when processing any frames from the first response from the server.

### Steps to reproduce the behavior

1. Client sends initial packet
2. server sends response
3. Client processes crypto frame and experiences an out of memory error and starts shutting down
4. Server sends a stateless retry packet to the client
5. Client starts processing stateless retry packet and hits an assert.

### Expected vs actual behavior

The client shouldn't process a stateless retry after successfully decrypting the server's first flight.

### PR DESCRIPTION
**Pull request by anrossi**
If a connection hasn't completed a handshake and is shutting down, but receives a retry packet after processing some data from the server, the connection hits an assert in QuicCryptoReset. The connection has already processed some of the server's flight, so it's too late for the server to send a retry packet. The connection is already shutting down, so there's no reason to retry.
This change skips the retry logic in this case.
Fixes #1767

### CODE REVIEW

File: src/core/connection.c [hunk 1]
```diff
@@ -3153,6 +3153,14 @@ QuicConnRecvRetry(
         return;
     }
 
+    //
+    // Make sure the connection is still active
+    //
+    if (Connection->State.ClosedLocally || Connection->State.ClosedRemotely) {
+        QuicPacketLogDrop(Connection, Packet, "Connection is shutting down");
```
Comment (nibanks) [inline src/core/connection.c:3160]:
```suggestion
        QuicPacketLogDrop(Connection, Packet, "Retry while shutting down");
```

**Review by nibanks — APPROVED** [review]
