### PR TITLE
Fix QUIC_TLS_SECRETS on Server and Client.

### LINKED ISSUE #2344: QUIC_TLS_SECRETS Not Fully Populated on Server
### Describe the bug

The `ClientRandom` isn't populated in the `QUIC_TLS_SECRETS` for the server side, because the code reads that from the TLS ClientHello before the connection is even indicated to the listener; meaning the app didn't have a chance to set the pointer to the struct to be written to.

### Affected OS

- [X] Windows Server 2022
- [X] Windows 11
- [X] Windows Insider Preview (specify affected build below)
- [X] Ubuntu
- [X] Debian
- [ ] Other (specify below)

### Additional OS information

_No response_

### MsQuic version

main

### Steps taken to reproduce bug

Try to query the `QUIC_TLS_SECRETS`.

### Expected behavior

They are fully populated.

### Actual outcome

Everything but `ClientRandom` is populated.

### Additional details

_No response_

### PR DESCRIPTION
**Pull request by anrossi**
## Description

 Fixes #2344
Specifically,
* Copies the ClientRandom on server side.
* Copies the ClientEarlyTrafficSecret on server side.
* Copies the ClientRandom on client side when 0-RTT is used.

## Testing

* Manual testing with quicinteropserver to ensure the ClientRandom is logged.
* New automated tests.

## Documentation

N/A

### CODE REVIEW

File: src/core/crypto.c [hunk 1]
```diff
@@ -1880,6 +1880,20 @@ QuicCryptoProcessData(
                 Connection->Paths[0].Binding,
                 Connection,
                 &Info);
+
+            if (!Connection->State.HandleClosed && Connection->State.ExternalOwner && Connection->TlsSecrets != NULL) {
```
Comment (nibanks) [inline src/core/crypto.c:1884]:
```suggestion
            if (!Connection->State.HandleClosed &&
                Connection->State.ExternalOwner &&
                Connection->TlsSecrets != NULL) {
```

**Comment by nibanks** [comment]
We should write a test that verifies the client and server secrets & random match.

**Comment by anrossi** [comment]
> We should write a test that verifies the client and server secrets & random match.

Gonna need to think about this a bit. It would involve recreating some TLS logic, and what exactly what it be compared against? 
The test hooks might not exist for this yet.

**Comment by nibanks** [comment]
> > We should write a test that verifies the client and server secrets & random match.
> 
> Gonna need to think about this a bit. It would involve recreating some TLS logic, and what exactly what it be compared against? The test hooks might not exist for this yet.

Just take a simple handshake test, update both sides to grab the secrets. After the handshake completes, compare the client and server secrets.

File: src/core/crypto.c [hunk 2]
```diff
@@ -1880,6 +1880,22 @@ QuicCryptoProcessData(
                 Connection->Paths[0].Binding,
                 Connection,
                 &Info);
+
+            if (!Connection->State.HandleClosed &&
```
Comment (anrossi) [inline src/core/crypto.c:1884]: Would appreciate a second pair of eyes on this. I'm not sure if this is the best way to tell that the connection has accepted.

Comment (nibanks) [reply src/core/crypto.c:1885]: I think this should be fine.

File: src/test/lib/DataTest.cpp [hunk 3]
```diff
@@ -512,6 +542,42 @@ QuicTestConnectAndPing(
...
+                for (auto j = 0u; j < ConnectionCount; j++) {
+                    auto ClientSecret = &ClientSecrets[j];
+                    if (!memcmp(
+                            ServerSecret->ClientRandom,
+                            ClientSecret->ClientRandom,
+                            sizeof(ClientSecret->ClientRandom))) {
+                        if (Match) {
+                            TEST_FAILURE("Multiple clients with the same ClientRandom?!");
+                            return;
+                        }
```
Comment (nibanks) [inline src/test/lib/DataTest.cpp:559]: This is theoretically possible, right? Just HIGHLY unlikely. Should we fail the tests if _somehow_ it happens?

**Review by nibanks — APPROVED** [review]

File: src/core/crypto.c [hunk 4]
```diff
@@ -1533,7 +1533,8 @@ QuicCryptoProcessTlsCompletion(
         //
         if (Connection->TlsSecrets != NULL &&
             QuicConnIsClient(Connection) &&
-            Crypto->TlsState.WriteKey == QUIC_PACKET_KEY_INITIAL &&
+            (Crypto->TlsState.WriteKey == QUIC_PACKET_KEY_INITIAL ||
+                Crypto->TlsState.WriteKey == QUIC_PACKET_KEY_0_RTT) &&
             Crypto->TlsState.BufferLength > 0) {
             QUIC_NEW_CONNECTION_INFO Info = { 0 };
             QuicCryptoTlsReadInitial(
```
[the remark this answers is not in the document]
Comment (nibanks) [reply src/core/crypto.c:1540]: In the Handshake/WithHandshakeArgs2.OldVersion/* tests. Does this get called twice or something in that case?

[the remark this answers is not in the document]
Comment (anrossi) [reply src/core/crypto.c:1540]: Still fails even with this line reverted, so it's something else that's leaking...

File: src/core/crypto_tls.c [hunk 5]
```diff
@@ -1744,6 +1744,9 @@ QuicCryptoTlsDecodeTransportParameters( // NOLINT(readability-function-size, goo
 
         case QUIC_TP_ID_VERSION_NEGOTIATION_EXT:
             if (Length > 0) {
+                if (TransportParams->VersionInfo != NULL) {
```
Comment (anrossi) [inline src/core/crypto_tls.c:1747]: Remove this; it's not this.

File: src/core/crypto_tls.c [hunk 6]
```diff
@@ -664,6 +656,32 @@ QuicCryptoTlsReadInitial(
...
+QUIC_STATUS
+QuicCryptoTlsReadClientRandom(
+    _In_ QUIC_CONNECTION* Connection,
+    _In_reads_(BufferLength)
+        const uint8_t* Buffer,
+    _In_ uint32_t BufferLength,
+    _Inout_ QUIC_TLS_SECRETS* TlsSecrets
+    )
+{
+    if (BufferLength < TLS_MESSAGE_HEADER_LENGTH + sizeof(uint16_t) + TLS_RANDOM_LENGTH) {
```
Comment (nibanks) [inline src/core/crypto_tls.c:669]: Can't you assert this instead? It was already validated with a previous call.

Comment (anrossi) [reply src/core/crypto_tls.c:669]: It'll generate a SAL issue without a check

**Review by nibanks — DISMISSED** [review]

**Review by nibanks — APPROVED** [review]

**Review by nibanks — APPROVED** [review]
