### PR TITLE
Fix only setting minimum mtu during config open failing

### LINKED ISSUE #2647: Cannot Set Min MTU without also Setting Max MTU
### Describe the bug

When an app sets a custom min MTU on a `QUIC_SETTINGS`, it fails to load.

### Affected OS

- [X] All
- [ ] Windows Server 2022
- [ ] Windows 11
- [ ] Windows Insider Preview (specify affected build below)
- [ ] Ubuntu
- [ ] Debian
- [ ] Other (specify below)

### Additional OS information

_No response_

### MsQuic version

main

### Steps taken to reproduce bug

Set min MTU only

### Expected behavior

Should succeed

### Actual outcome

Fails

### Additional details

_No response_

### PR DESCRIPTION
**Pull request by thhous-msft**
## Description

Closes #2647. Setting a minimum mtu only during ConfigurationOpen results in a failure, because the default values are 0. Set the default values to things more sane.

Also fixes a bug where minimum can be higher then maximum, if only 1 value is set on the configuration, and the global value is not within the bounds.

## Testing

New test added to cover case

## Documentation
N/A

### CODE REVIEW

File: src/core/settings.c [hunk 1]
```diff
@@ -501,10 +503,8 @@ QuicSettingApply(
         if (MinimumMtu > MaximumMtu) {
             return FALSE;
         }
-        if (Destination->MinimumMtu != MinimumMtu) {
+        if (Source->IsSet.MinimumMtu || Source->IsSet.MaximumMtu) {
             Destination->IsSet.MinimumMtu = TRUE;
-        }
-        if (Destination->MaximumMtu != MaximumMtu) {
```
Comment (nibanks) [inline src/core/settings.c:507]: I don't understand this removal

Comment (thhous-msft) [reply src/core/settings.c:507]: Thats to solve the 2nd bug found. Basically if we set the minimum, we have to implictly set the maximum. Otherwise, when the global settings are loaded in, they can result in an out of sync state.

Comment (nibanks) [reply src/core/settings.c:507]: If setting the min doesn't modify the max, then I don't quite understand what the problem is here.

Comment (nibanks) [reply src/core/settings.c:507]: Generally, we need to decide priority here. Usually the order is parent < registry < app. But if the app only sets the min and the registry needs to set a max, and they don't conflict that should be supported.

Comment (thhous-msft) [reply src/core/settings.c:507]: Well then we need to change loading from registry and global to be able to error.

Comment (nibanks) [reply src/core/settings.c:507]: Why? And where is that error going to go? Right now, any errors in there fail silently and have fallback code.

Comment (thhous-msft) [reply src/core/settings.c]: I found a way to do it silently, and added more tests.

**Review by nibanks — APPROVED** [review]

**Review by nibanks — APPROVED** [review]
