### PR TITLE
Correctly initialize the ip address when setting QUIC_ADDR to the loopback address

### LINKED ISSUE #3969: QuicAddrSetToLoopback does not fill remaining bytes with zero
### Describe the bug

void
QuicAddrSetToLoopback(
    _Inout_ QUIC_ADDR* Addr
    )
{
    if (Addr->si_family == QUIC_ADDRESS_FAMILY_INET) {
        Addr->Ipv4.sin_addr.S_un.S_un_b.s_b1 = 127;
        Addr->Ipv4.sin_addr.S_un.S_un_b.s_b4 = 1;
    } else {
        Addr->Ipv6.sin6_addr.u.Byte[15] = 1;
    }
}

For example, in ipv6 case Addr->Ipv6.sin6_addr.u.Byte[0] ... Addr->Ipv6.sin6_addr.u.Byte[14] are unchanged.
Is this intended behavior that requires the input to be preinitialized with 0? 

### Affected OS

- [ ] Windows
- [ ] Linux
- [ ] macOS
- [ ] Other (specify below)

### Additional OS information

_No response_

### MsQuic version

main

### Steps taken to reproduce bug

QUIC_ADDR loopback;
QuicAddrSetFamily(&loopback,QUIC_ADDRESS_FAMILY_INET6);
QuicAddrSetToLoopback(&loopback);

### Expected behavior

loopback properly set to ::1

### Actual outcome

uninitialized garbage

### Additional details

_No response_

### PR DESCRIPTION
**Pull request by sm-msft**
## Description

Fixes #3969.

- Initialize address field when setting given QUIC_ADDR to loopback address
- Basic tests for several QuicAddr* API

## Testing

Some existing tests hit this code path and new tests have been added for specific checks.

## Documentation

No

### CODE REVIEW

File: src/test/MsQuicTests.h [hunk 1]
```diff
@@ -780,6 +781,11 @@ typedef struct {
     QUIC_CTL_CODE(15, METHOD_BUFFERED, FILE_WRITE_DATA)
     // int - Family
 
+#define IOCTL_QUIC_RUN_TEST_ADDR_FUNCTIONS \
+    QUIC_CTL_CODE(16, METHOD_BUFFERED, FILE_WRITE_DATA)
```
Comment (nibanks) [inline src/test/MsQuicTests.h:785]: This must be added to the end of the file/list. There is already a `16` defined below.

File: src/test/lib/BasicTest.cpp [hunk 2]
```diff
@@ -270,3 +270,26 @@ void QuicTestBindConnectionExplicit(_In_ int Family)
...
+    QuicAddrSetFamily(&SockAddr, QuicAddrFamily);
+    TEST_TRUE(QuicAddrGetFamily(&SockAddr) == QuicAddrFamily);
+
+    if (QuicAddrFamily == QUIC_ADDRESS_FAMILY_INET) {
+        SockAddr.Ipv4.sin_addr.s_addr = 0x00FFFF00UL;
+        QuicAddrSetToLoopback(&SockAddr);
+        TEST_TRUE(SockAddr.Ipv4.sin_addr.s_host == 0);
+        TEST_TRUE(SockAddr.Ipv4.sin_addr.s_lh == 0);
+    }
+    else {
```
Comment (nibanks) [inline src/test/lib/BasicTest.cpp:287]: nit: style
```suggestion
    } else {
```

File: src/test/lib/BasicTest.cpp [hunk 3]
```diff
@@ -270,3 +270,26 @@ void QuicTestBindConnectionExplicit(_In_ int Family)
...
+{
+    QUIC_ADDR SockAddr = {};
+    QUIC_ADDRESS_FAMILY QuicAddrFamily = (Family == 4) ? QUIC_ADDRESS_FAMILY_INET : QUIC_ADDRESS_FAMILY_INET6;
+    QuicAddrSetFamily(&SockAddr, QuicAddrFamily);
+    TEST_TRUE(QuicAddrGetFamily(&SockAddr) == QuicAddrFamily);
+
+    if (QuicAddrFamily == QUIC_ADDRESS_FAMILY_INET) {
+        SockAddr.Ipv4.sin_addr.s_addr = 0x00FFFF00UL;
+        QuicAddrSetToLoopback(&SockAddr);
+        TEST_TRUE(SockAddr.Ipv4.sin_addr.s_host == 0);
```
Comment (nibanks) [inline src/test/lib/BasicTest.cpp:284]: I _think_ most of the direct access you're doing for the inner variables of the IP address won't work cross platform.

File: src/inc/msquic_winuser.h [hunk 4]
```diff
@@ -259,9 +259,11 @@ QuicAddrSetToLoopback(
     )
 {
     if (Addr->si_family == QUIC_ADDRESS_FAMILY_INET) {
+        Addr->Ipv4.sin_addr.s_addr = 0UL;
```
Comment (nibanks) [inline src/inc/msquic_winuser.h:262]: What about msquic_posix.h?

File: src/test/bin/winkernel/control.cpp [hunk 5]
```diff
@@ -525,6 +525,7 @@ size_t QUIC_IOCTL_BUFFER_SIZES[] =
     0,
     sizeof(BOOLEAN),
     sizeof(INT32),
+    sizeof(INT32),                           // IOCTL_QUIC_RUN_TEST_ADDR_FUNCTIONS
```
Comment (nibanks) [inline src/test/bin/winkernel/control.cpp:528]: Comment is unnecessary

File: src/test/lib/BasicTest.cpp [hunk 6]
```diff
@@ -270,3 +270,24 @@ void QuicTestBindConnectionExplicit(_In_ int Family)
         TEST_QUIC_SUCCEEDED(Status);
     }
 }
+
+void QuicTestAddrFunctions(_In_ int Family)
+{
+    QUIC_ADDR SockAddr = {};
```
Comment (nibanks) [inline src/test/lib/BasicTest.cpp:276]: I feel like we should explicitly memset this to `0xFF` first, to make sure the checks below would fail if they aren't setting everything properly.

File: src/inc/msquic_winuser.h (hunk 4 above)
Comment (sm-msft) [reply src/inc/msquic_winuser.h:262]: `    if (Addr->Ip.sa_family == QUIC_ADDRESS_FAMILY_INET) {
        Addr->Ipv4.sin_addr.s_addr = htonl(INADDR_LOOPBACK);
    } else {
        Addr->Ipv6.sin6_addr = in6addr_loopback;
    }
`
Posix code initializes s_addr as a whole without manipulating individual bytes. We dont need to change it.

As far as uniformity of the code goes, I am unsure if these constants used in Posix code are defined in the non-posix code as well.

Comment (nibanks) [reply src/inc/msquic_winuser.h:262]: Ok. Sounds good!

File: src/test/bin/winkernel/control.cpp (hunk 5 above)
Comment (sm-msft) [reply src/test/bin/winkernel/control.cpp:528]: This comment makes it easy to associate the IOCTL with the array entry, implying that new ioctls need entries here.

Comment (sm-msft) [reply src/test/bin/winkernel/control.cpp:528]: I hope you dont mind me leaving this in place. Searching for this IOCTL name will pull up all relevant locations and makes it easy for someone new to make further additions. IMO this array does not standout otherwise.

**Review by nibanks — APPROVED** [review]
