### PR TITLE
Fix race condition in Ping tests

### LINKED ISSUE #395: Test Code Use-After-Free
### Describe the bug

Looks like a test bug incorrectly using a stream after it's been cleaned up.

https://microsoft.visualstudio.com/OS/_build/results?buildId=23707789&view=logs&j=85d09e18-ccbb-59e4-1e11-3bc3359c994e&t=0d6cb4be-3528-587f-fd98-c4579db4f471

```
Note: Google Test filter = AppData/WithSendArgs3.SendIntermittently/71
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
Initializing for User Mode tests
[----------] 1 test from AppData/WithSendArgs3
[ RUN      ] AppData/WithSendArgs3.SendIntermittently/71

=================================================================
==17874==ERROR: AddressSanitizer: heap-use-after-free on address 0x607000002330 at pc 0x555dee108f46 bp 0x7ffd165f9c30 sp 0x7ffd165f9c20
READ of size 8 at 0x607000002330 thread T0
    #0 0x555dee108f45 in TestStream::StartPing(unsigned long) /home/vsts/work/1/s/src/test/lib/TestStream.cpp:119
    #1 0x555dee0db2e0 in SendPingBurst(TestConnection*, unsigned int, unsigned long) /home/vsts/work/1/s/src/test/lib/DataTest.cpp:200
    #2 0x555dee0dd7af in QuicTestConnectAndPing /home/vsts/work/1/s/src/test/lib/DataTest.cpp:432
    #3 0x555dedfca821 in WithSendArgs3_SendIntermittently_Test::TestBody() /home/vsts/work/1/s/src/test/bin/quic_gtest.cpp:662
    #4 0x555dee140c21 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /home/vsts/work/1/s/submodules/googletest/googletest/src/gtest.cc:2671
    #5 0x555dee11b81d in testing::Test::Run() /home/vsts/work/1/s/submodules/googletest/googletest/src/gtest.cc:2688
    #6 0x555dee11c1c4 in testing::TestInfo::Run() /home/vsts/work/1/s/submodules/googletest/googletest/src/gtest.cc:2865
    #7 0x555dee11ca5e in testing::TestSuite::Run() /home/vsts/work/1/s/submodules/googletest/googletest/src/gtest.cc:3019
    #8 0x555dee128be4 in testing::internal::UnitTestImpl::RunAllTests() /home/vsts/work/1/s/submodules/googletest/googletest/src/gtest.cc:5711
    #9 0x555dee141bdf in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /home/vsts/work/1/s/submodules/googletest/googletest/src/gtest.cc:2671
    #10 0x555dee1273eb in testing::UnitTest::Run() /home/vsts/work/1/s/submodules/googletest/googletest/src/gtest.cc:5294
    #11 0x555dedfbc016 in RUN_ALL_TESTS() /home/vsts/work/1/s/submodules/googletest/googletest/include/gtest/gtest.h:2485
    #12 0x555dedfbc016 in main /home/vsts/work/1/s/src/test/bin/quic_gtest.cpp:1049
    #13 0x7fcec20d7b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
    #14 0x555dedfb9bc9 in _start (/home/vsts/work/1/s/artifacts/linux/x64_Debug_stub/msquictest+0x2bbc9)
0x607000002330 is located 16 bytes inside of 72-byte region [0x607000002320,0x607000002368)
freed by thread T4 here:
    #0 0x7fcec36199c8 in operator delete(void*, unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xe19c8)
    #1 0x555dee0da987 in PingStreamShutdown /home/vsts/work/1/s/src/test/lib/DataTest.cpp:178
    #2 0x555dee10a4bb in TestStream::HandleStreamEvent(QUIC_STREAM_EVENT*) /home/vsts/work/1/s/src/test/lib/TestStream.cpp:364
    #3 0x555dee10a5a3 in TestStream::QuicStreamHandler(QUIC_HANDLE*, void*, QUIC_STREAM_EVENT*) /home/vsts/work/1/s/src/test/lib/TestStream.h:150

    #4 0x7fcec308414c in QuicStreamIndicateEvent /home/vsts/work/1/s/src/core/stream.c:339
    #5 0x7fcec3084929 in QuicStreamIndicateShutdownComplete /home/vsts/work/1/s/src/core/stream.c:402
    #6 0x7fcec3084e4b in QuicStreamTryCompleteShutdown /home/vsts/work/1/s/src/core/stream.c:476
    #7 0x7fcec3086f42 in QuicStreamReceiveComplete /home/vsts/work/1/s/src/core/stream_recv.c:892
    #8 0x7fcec30871e0 in QuicStreamRecvFlush /home/vsts/work/1/s/src/core/stream_recv.c:783
    #9 0x7fcec30b5867 in QuicConnDrainOperations /home/vsts/work/1/s/src/core/connection.c:6092
    #10 0x7fcec3092d8a in QuicWorkerProcessConnection /home/vsts/work/1/s/src/core/worker.c:477
    #11 0x7fcec3093639 in QuicWorkerThread /home/vsts/work/1/s/src/core/worker.c:565
    #12 0x7fcec2e386da in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76da)

previously allocated by thread T0 here:
    #0 0x7fcec3618448 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xe0448)
    #1 0x555dee108cc7 in TestStream::FromConnectionHandle(QUIC_HANDLE*, void (*)(TestStream*), QUIC_STREAM_OPEN_FLAGS) /home/vsts/work/1/s/src/test/lib/TestStream.cpp:81
    #2 0x555dee103c35 in TestConnection::NewStream(void (*)(TestStream*), QUIC_STREAM_OPEN_FLAGS) /home/vsts/work/1/s/src/test/lib/TestConnection.cpp:122
    #3 0x555dee0db294 in SendPingBurst(TestConnection*, unsigned int, unsigned long) /home/vsts/work/1/s/src/test/lib/DataTest.cpp:195
    #4 0x555dee0dd7af in QuicTestConnectAndPing /home/vsts/work/1/s/src/test/lib/DataTest.cpp:432
    #5 0x555dedfca821 in WithSendArgs3_SendIntermittently_Test::TestBody() /home/vsts/work/1/s/src/test/bin/quic_gtest.cpp:662
    #6 0x555dee140c21 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /home/vsts/work/1/s/submodules/googletest/googletest/src/gtest.cc:2671
    #7 0x555dee11b81d in testing::Test::Run() /home/vsts/work/1/s/submodules/googletest/googletest/src/gtest.cc:2688
    #8 0x555dee11c1c4 in testing::TestInfo::Run() /home/vsts/work/1/s/submodules/googletest/googletest/src/gtest.cc:2865
    #9 0x555dee11ca5e in testing::TestSuite::Run() /home/vsts/work/1/s/submodules/googletest/googletest/src/gtest.cc:3019
    #10 0x555dee128be4 in testing::internal::UnitTestImpl::RunAllTests() /home/vsts/work/1/s/submodules/googletest/googletest/src/gtest.cc:5711
    #11 0x555dee141bdf in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /home/vsts/work/1/s/submodules/googletest/googletest/src/gtest.cc:2671
    #12 0x555dee1273eb in testing::UnitTest::Run() /home/vsts/work/1/s/submodules/googletest/googletest/src/gtest.cc:5294
    #13 0x555dedfbc016 in RUN_ALL_TESTS() /home/vsts/work/1/s/submodules/googletest/googletest/include/gtest/gtest.h:2485
    #14 0x555dedfbc016 in main /home/vsts/work/1/s/src/test/bin/quic_gtest.cpp:1049
    #15 0x7fcec20d7b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)

Thread T4 created by T0 here:
    #0 0x7fcec356fd2f in __interceptor_pthread_create (/usr/lib/x86_64-linux-gnu/libasan.so.4+0x37d2f)
    #1 0x7fcec30fe3d2 in QuicThreadCreate /home/vsts/work/1/s/src/platform/platform_linux.c:941
    #2 0x7fcec309144b in QuicWorkerInitialize /home/vsts/work/1/s/src/core/worker.c:73
    #3 0x7fcec3093d4c in QuicWorkerPoolInitialize /home/vsts/work/1/s/src/core/worker.c:703
    #4 0x7fcec307cf84 in MsQuicRegistrationOpen /home/vsts/work/1/s/src/core/registration.c:99
    #5 0x555dee010d63 in QuicTestEnvironment::SetUp() /home/vsts/work/1/s/src/test/bin/quic_gtest.cpp:40
    #6 0x555dee1287a2 in SetUpEnvironment /home/vsts/work/1/s/submodules/googletest/googletest/src/gtest.cc:5590
    #7 0x555dee1496e6 in void (*std::for_each<__gnu_cxx::__normal_iterator<testing::Environment* const*, std::vector<testing::Environment*, std::allocator<testing::Environment*> > >, void (*)(testing::Environment*)>(__gnu_cxx::__normal_iterator<testing::Environment* const*, std::vector<testing::Environment*, std::allocator<testing::Environment*> > >, __gnu_cxx::__normal_iterator<testing::Environment* const*, std::vector<testing::Environment*, std::allocator<testing::Environment*> > >, void (*)(testing::Environment*)))(testing::Environment*) /usr/include/c++/7/bits/stl_algo.h:3884
    #8 0x555dee14238e in void testing::internal::ForEach<std::vector<testing::Environment*, std::allocator<testing::Environment*> >, void (*)(testing::Environment*)>(std::vector<testing::Environment*, std::allocator<testing::Environment*> > const&, void (*)(testing::Environment*)) /home/vsts/work/1/s/submodules/googletest/googletest/src/gtest-internal-inl.h:303
    #9 0x555dee128a71 in testing::internal::UnitTestImpl::RunAllTests() /home/vsts/work/1/s/submodules/googletest/googletest/src/gtest.cc:5689
    #10 0x555dee141bdf in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /home/vsts/work/1/s/submodules/googletest/googletest/src/gtest.cc:2671
    #11 0x555dee1273eb in testing::UnitTest::Run() /home/vsts/work/1/s/submodules/googletest/googletest/src/gtest.cc:5294
    #12 0x555dedfbc016 in RUN_ALL_TESTS() /home/vsts/work/1/s/submodules/googletest/googletest/include/gtest/gtest.h:2485
    #13 0x555dedfbc016 in main /home/vsts/work/1/s/src/test/bin/quic_gtest.cpp:1049
    #14 0x7fcec20d7b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)

SUMMARY: AddressSanitizer: heap-use-after-free /home/vsts/work/1/s/src/test/lib/TestStream.cpp:119 in TestStream::StartPing(unsigned long)
Shadow bytes around the buggy address:
  0x0c0e7fff8410: fd fd fd fd fd fd fd fd fd fd fa fa fa fa fd fd
  0x0c0e7fff8420: fd fd fd fd fd fd fd fa fa fa fa fa fd fd fd fd
  0x0c0e7fff8430: fd fd fd fd fd fa fa fa fa fa fd fd fd fd fd fd
  0x0c0e7fff8440: fd fd fd fa fa fa fa fa fd fd fd fd fd fd fd fd
  0x0c0e7fff8450: fd fa fa fa fa fa fd fd fd fd fd fd fd fd fd fa
=>0x0c0e7fff8460: fa fa fa fa fd fd[fd]fd fd fd fd fd fd fa fa fa
  0x0c0e7fff8470: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0e7fff8480: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0e7fff8490: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0e7fff84a0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0e7fff84b0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==17874==ABORTING

```

### Steps to reproduce the behavior

Randomly occurred during a test run. I've seen it a couple of times. Not that common.

### PR DESCRIPTION
**Pull request by ThadHouse**
In StartPing, when the QUIC_SEND_FLAG_FIN flag is set and there are no bytes left, if the SteamSend completes successfully, we are racing against stream callback, which deletes the instance we are currently executing. When the loop continues, BytesToSend is read again, which is the use after free. Explicitly exiting the loop upon no data left removes the race

Closes #395

### CODE REVIEW

File: src/test/lib/TestStream.cpp [hunk 1]
```diff
@@ -146,6 +146,12 @@ TestStream::StartPing(
                 TEST_FAILURE("MsQuic->StreamSend failed, 0x%x.", Status);
                 return false;
             }
+            if (resultingBytesLeft == 0) {
+                // On the finish packet if it succeeds, the instance
+                // we are executing in will be deleted. Return
+                // so we don't execute the while on a deleted instance.
```
Comment (nibanks) [inline src/test/lib/TestStream.cpp:152]: If `resultingBytesLeft` is zero, then shouldn't `BytesToSend` also be zero? If it is, then wouldn't the while loop terminate right after this anyways?

Comment (ThadHouse) [reply src/test/lib/TestStream.cpp:152]: Its reading the BytesToSend that is the use after free. Because the execution of `StartPing` could be preempted, allowing the callback that eventually deletes the TestStream instance to run before the iteration of the while loop occurs.

Comment (nibanks) [reply src/test/lib/TestStream.cpp:152]: Ah... I see now. Thanks.
