### PR TITLE
Use UDP Length for XDP RX

### LINKED ISSUE #3776: UDP parsing logic does not honor UDP length field
### Describe the bug

UDP parsing logic does not honor UDP length field. It infers the payload length from IP layer.

### Affected OS

- [X] Windows
- [ ] Linux
- [ ] macOS
- [ ] Other (specify below)

### Additional OS information

_No response_

### MsQuic version

main

### Steps taken to reproduce bug

1. Receive a UDP packet whose IP payload is greater than UDP payload.

### Expected behavior

Data after UDP payload should not be accepted

### Actual outcome

Data after UDP payload will be indicated up

### Additional details

_No response_

### PR DESCRIPTION
**Pull request by nibanks**
## Description

Uses the UDP length field instead of the IP length for receiving the UDP payload. Fixes #3776.

## Testing

CI

## Documentation

N/A

### CODE REVIEW

File: src/platform/datapath_raw_socket.c [hunk 1]
```diff
@@ -118,14 +118,24 @@ CxPlatDpRawParseUdp(
...
+        QuicTraceEvent(
+            DatapathErrorStatus,
+            "[data][%p] ERROR, %u, %s.",
+            Datapath,
+            Length,
+            "UDP Length larger than IP length");
+        return;
+    }
+
     Length -= sizeof(UDP_HEADER);
```
Comment (csujedihy) [inline src/platform/datapath_raw_socket.c:131]: We should remove this. It's not used.

File: src/platform/datapath_raw_socket.c [hunk 2]
```diff
@@ -118,14 +118,24 @@ CxPlatDpRawParseUdp(
         return;
     }
 
+    if (Length < QuicNetByteSwapShort(Udp->Length)) {
```
Comment (csujedihy) [inline src/platform/datapath_raw_socket.c:121]: nit: maybe we should store the UDP length from UDP header in a local var so we don't have to do the swap twice. Though, that swap might be completely optimized out.

**Comment by csujedihy** [comment]
Solving #3776

File: src/platform/datapath_raw_socket.c (hunk 2 above)
Comment (nibanks) [reply src/platform/datapath_raw_socket.c:121]: I'll leave it as is for now. Let's see if the compiler can deal with it.

**Review by csujedihy — APPROVED** [review]

**Review by csujedihy — COMMENTED** [review]
Is sidecar needed to be updated?

**Comment by nibanks** [comment]
> Is sidecar needed to be updated?

No, because it's using an existing event with new payload.
