### PR TITLE
Don't call DisableThreadLibraryCalls with static CRT

### LINKED ISSUE #437: DisableThreadLibraryCalls should not be used with static CRT
### Describe the bug

According to https://docs.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-disablethreadlibrarycalls DisableThreadLibraryCalls should not be used if the static CRT is used. Not sure exactly what would break, but violating documented practices is never a good thing.

### PR DESCRIPTION
**Pull request by ThadHouse**
Closes #437

### CODE REVIEW

File: src/bin/winuser/dllmain.c [hunk 1]
```diff
@@ -34,7 +34,9 @@ DllMain(
     switch (Reason) {
 
     case DLL_PROCESS_ATTACH:
+#ifndef _MT
```
Comment (nibanks) [inline src/bin/winuser/dllmain.c:37]: Can you put a comment on this line (and in the other file) saying something like "Don't disable thread library calls with static CRT!"

Comment (ThadHouse) [reply src/bin/winuser/dllmain.c:40]: Done

Comment (nibanks) [reply src/bin/winuser/dllmain.c:40]: Just put the comment on the same line as the #ifdef please:
```
#ifndef _MT // Don't disable thread library calls with static CRT!
```
